apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-namespace
  labels:
    app: todo-api
spec:
    replicas: 2
    selector:
        matchLabels:
          app: todo-api
    template:
        metadata:
          labels:
            app: todo-api
        spec:
          containers:
          - name: todo-api
            image: only1adwy/todo-api:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            env:
            - name: SqliteConnection
              value: "Data Source=Database/todo.db"
            - name: PORT
              value: "8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
  