using System;
using System.Collections.Generic;

namespace Todo.Api.Models.Entities;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>
///     Represents a list of tasks that a user can create.
///     A list can have many tasks.
///     A list belongs to a user.
/// </summary>
public class TaskList
{
    /// <summary>
    ///     The unique identifier of the list of tasks, autogenerated, and not null.
    /// </summary>
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    ///     The name of the list of tasks, required, and not null.
    ///     The name must be between 1 and 100 characters.
    /// </summary>
    [Required]
    [StringLength(100, MinimumLength = 1)]
    public required string Name { get; set; }

    /// <summary>
    ///     The description of the list of tasks, not required, and can be null.
    ///     The description must not exceed 200 characters.
    /// </summary>
    [StringLength(200)]
    public string Description { get; set; }

    /// <summary>
    ///     The list of tasks that belong to the list of tasks, required, and not null.
    ///     A list can have many tasks.
    ///     The list of tasks is initialized as an empty list.
    ///     The list of tasks is not lazy-loaded, and the tasks are eagerly-loaded.
    ///     The list is not mapped to the database.
    /// </summary>
    [Required]
    public virtual List<Task> Tasks { get; set; } = [];

    /// <summary>
    ///     The user that the list of tasks belongs to, not required, and can be null.
    ///     A list belongs to a user.
    /// </summary>
    [ForeignKey("UserId")]
    public string? UserId { get; set; }
}