pipeline {
    agent any

    environment {
        KUBECONFIG = '/var/lib/jenkins/kubernetes/config' // Make sure this path is correct
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/moheladwy/TodoFullstack'
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'ansible/playbook.yaml',
                    inventory: 'ansible/inventory.ini'
                )
            }
        }
    }

    post {
        always {
            cleanWs()
            echo "Workspace cleaned up after pipeline completion."
        }

        failure {
            echo "Pipeline failed."
        }

        success {
            echo "Pipeline completed successfully."
        }
    }
}
