name: Docker Image Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: echo ${{ secrets.DOCKERHUB_USERNAME }} | wc -c

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          DATE_TAG=$(date +%s)
          docker build --tag todo-fullstack:$DATE_TAG .

      - name: Tag the Docker image
        run: |
          docker tag todo-fullstack:$DATE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:$DATE_TAG
          docker tag todo-fullstack:$DATE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:latest

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:$DATE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-api:latest
