name: Docker Image Deploy for React Client

on:
    push:
        branches: ["main"]
        paths:
            - "client/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set date tag
              run: echo "DATE_TAG=$(date +%s)" >> $GITHUB_ENV

            - name: Build the Docker image
              run: |
                  docker build \
                  --build-arg VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }} \
                  --build-arg VITE_SERVER_LOGIN_PATH=Auth/login \
                  --build-arg VITE_SERVER_REGISTER_PATH=Auth/register \
                  --build-arg VITE_SERVER_REFRESH_PATH=Auth/refresh \
                  --build-arg VITE_SERVER_LOGOUT_PATH=Auth/logout \
                  -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-client:${{ env.DATE_TAG }} client
                  
            - name: Tag the Docker image
              run: |
                  # Tag with timestamp
                  docker tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-client:${{ env.DATE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/todo-client:${{ env.DATE_TAG }}
                  # Tag as latest
                  docker tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-client:${{ env.DATE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/todo-client:latest

            - name: Push the Docker image
              run: |
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-client:${{ env.DATE_TAG }}
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-client:latest
