name: C# Lint

on:
    push:
        branches:
            - main
            - test
    pull_request:
        branches:
            - main
            - test

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.x"

            - name: Install dependencies
              run: dotnet restore

            - name: Run StyleCop linting
              run: dotnet build /warnaserror /p:TreatWarningsAsErrors=true
