name: C# Lint

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'
jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.x"

            - name: Install dependencies
              run: dotnet restore api/api.csproj

            - name: Run StyleCop linting
              run: dotnet build api /warnaserror /p:TreatWarningsAsErrors=true
